import type { JsonReport } from "../json-report.js";
import { REPORT_CLIENT_SCRIPT } from "./client-script.js";
import { escapeHtml, escapeJsonForScriptTag } from "./escape.js";
import { REPORT_STYLES } from "./styles.js";

/**
 * A restrictive CSP for a report that must work by double-clicking a local
 * file (PLAN.md §31: "apply a restrictive Content Security Policy... where
 * practical", "do not load external scripts or fonts", "do not make
 * network requests"). `'unsafe-inline'` is unavoidable without a server to
 * hand out per-request nonces — everything inline is generated by this
 * file, not derived from scanned file content, so it carries no injection
 * risk on its own; the actual escaping work is in `escape.ts`.
 *
 * `frame-ancestors` is deliberately omitted: browsers ignore it entirely
 * when delivered via `<meta>` (it only takes effect as a real HTTP
 * response header), so including it here would just be dead weight that
 * logs a console warning on every load.
 */
const CONTENT_SECURITY_POLICY = [
  "default-src 'none'",
  "img-src 'self' data:",
  "style-src 'unsafe-inline'",
  "script-src 'unsafe-inline'",
  "connect-src 'none'",
  "base-uri 'none'",
  "form-action 'none'",
].join("; ");

/**
 * Renders the complete, self-contained static HTML review report
 * (PLAN.md §20). The report's own JSON data is embedded inline (not
 * fetched) so the page works when opened directly via `file://` — fetch()
 * of a sibling file is unreliable across browsers under that scheme,
 * unlike `<img>`, which loads local relative paths fine.
 */
export function renderReportHtml(report: JsonReport): string {
  const dataJson = escapeJsonForScriptTag(JSON.stringify(report));
  const title = `image-origin report — ${report.images.length} images, ${report.groups.length} groups`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="${escapeHtml(CONTENT_SECURITY_POLICY)}">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<style>${REPORT_STYLES}</style>
</head>
<body>
<header>
  <h1>image-origin review report</h1>
  <div id="summary-generated"></div>
</header>
<div class="layout">
  <aside class="sidebar">
    <div class="filters">
      <div class="filters-row">
        <label style="flex:1">Min confidence
          <input type="range" id="filter-confidence" min="0" max="100" value="0">
        </label>
        <span id="filter-confidence-value">0%</span>
      </div>
      <label>Relationship
        <select id="filter-relationship">
          <option value="">All relationships</option>
        </select>
      </label>
      <label style="flex-direction:row; align-items:center; gap:6px;">
        <input type="checkbox" id="filter-unresolved">
        Show only unresolved groups
      </label>
      <div class="filters-row">
        <span id="group-count"></span>
        <button type="button" class="btn" id="export-decisions">Export decisions</button>
      </div>
    </div>
    <div id="group-list"></div>
  </aside>
  <main id="group-detail"></main>
</div>
<script type="application/json" id="report-data">${dataJson}</script>
<script>${REPORT_CLIENT_SCRIPT}</script>
</body>
</html>
`;
}
